<?php
    // Ensure session is started before requiring config/db.php
    // db.php might rely on session_start() implicitly or explicitly
    if (session_status() == PHP_SESSION_NONE) {
        session_start();
    }

    require_once 'config/db.php';
    // Check if user is logged in
    if (!isset($_SESSION['user_id'])) {
        header('Location: login.php');
        exit();
    }
    $user_id = $_SESSION['user_id'];
    // Fetch user details
    $result = $conn->query("SELECT username, coins FROM users WHERE id = $user_id");
    if ($result->num_rows > 0) {
         $user = $result->fetch_assoc();
    } else {
         // Handle case where user might be in session but not in DB (shouldn't happen with proper flow)
         // Log them out or show an error
         header('Location: logout.php');
         exit();
    }
?>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Mines Game</title>
    <link rel="stylesheet" href="assets/css/style.css">
    <!-- You might want to add a favicon -->
    <!-- <link rel="icon" href="assets/images/favicon.png" type="image/png"> -->
    <!-- REMOVED: Inline styles for withdrawal section -->
    <style>
        /* Any specific styles needed *only* for the game page */
        /* Keep game-specific styles here if they aren't in style.css */
        /* Example: */
         .withdrawal-button-container {
            margin-top: 5px;
            margin-left: 0px; /* Space it from logout button */
         }
        .withdrawal-button {
            background-color:rgb(53, 164, 38); /* Example color */
            color: white;
            text-decoration: none;
            padding: 8px 15px;
            border-radius: 5px;
            font-weight: bold;
            transition: background-color 0.2s ease;
            white-space: nowrap;
            display: inline-block; /* Ensure padding/margins work */
        }
        .withdrawal-button:hover {
            background-color: #f57c00; /* Darker orange */
        }
    </style>
</head>
<body class="new-layout">
    <header>
        <div class="header-left">
             <img src="assets/images/GAMELOGO.png" alt="ALUMNI Logo" class="logo">
             <span class="site-title"></span>
        </div>
        <div class="header-center">
             <div class="user-balance-display">
                COINS: <span id="user-balance"><?php echo number_format($user['coins'], 2); ?></span>
             </div>
        </div>
        <div class="header-right">
            <!-- NEW: Withdrawal Button -->
            <div class="withdrawal-button-container">
                <a href="withdrawal.php" class="withdrawal-button">Withdraw</a>
            </div>
            <div class="withdrawal-button-container">
             <a href="logout.php" class="withdrawal-button">Logout</a>
    </div>
        </div>
    </header>

    <!-- Promotional Banner -->
    <div class="promo-banner">
         <p id="jackpot-banner-text">Loading jackpot info...</p>
    </div>

    <!-- NEW: Main Content Container for Desktop Side-by-Side Layout -->
    <div class="main-content-container">

        <!-- Game Wrapper (Contains core game UI elements: Grid, Stats, Multiplier, Controls) -->
        <div class="game-wrapper">
            <!-- Container for Grid and side stats -->
            <div class="game-main-area">
                <div class="grid-stats">
                    <div class="stat-item">
                        <img src="assets/images/coin.png" alt="Coins">
                        <span id="stats-coins-count">0</span>
                        <label>COINS</label>
                    </div>
                    <div class="stat-item">
                        <img src="assets/images/bomb.png" alt="Bombs">
                        <span id="stats-bombs-count">4</span>
                         <label>BOMBS</label>
                    </div>
                </div>

                <div class="game-grid-container">
                    <div id="game-grid">
                        <!-- Tiles will be generated by JS -->
                    </div>
                </div>
            </div>

            <!-- Horizontal Multiplier Carousel -->
            <div class="multiplier-carousel">
                 <!-- Nav arrows will be handled by JS if implemented -->
                 <div id="multiplier-list" class="multiplier-list-horizontal">
                     <!-- Multipliers will be populated by JS -->
                </div>
                 <!-- Nav arrows -->
            </div>

            <!-- Bottom Controls Panel -->
            <div class="controls-panel-bottom">
                <div class="bet-selection-area">
                     <div class="bet-amount-input-area">
                         <!-- Container for Peso symbol and Input side-by-side -->
                         <div class="bet-input-row">
                             <label>₱</label>
                            <input type="number" id="bet-amount" value="10" step="1">
                         </div>
                         <!-- Display for Total Winnings -->
                         <div class="current-winnings-display">
                             <label>WINNINGS:</label>
                             ₱ <span id="current-winnings-amount">0.00</span>
                         </div>
                     </div>
                </div>
                <button id="start-game-btn" class="bet-button">Bet</button>
<div class="mines-setttings">
                 <div class="mines-selection-area">
                     <label for="bomb-select">MINES:</label>
                     <select id="bomb-select">
                         <?php for ($i = 1; $i <= 24; $i++): ?>
                             <option value="<?php echo $i; ?>" <?php if ($i == 4) echo 'selected'; ?>><?php echo $i; ?></option>
                         <?php endfor; ?>
                     </select>
                     <button id="auto-select-btn">Auto Select</button>
                 </div>
                 <!-- Cash Out button location -->
                 <button id="cashout-btn" disabled class="cashout-button">Cash Out</button>
            </div>
                         </div>
             <!-- End Bottom Controls Panel -->

        </div> <!-- End .game-wrapper -->

        <!-- NEW: Side Panels Container for Desktop -->
        <div class="side-panels-container">
            <!-- Recent Plays -->
            <div class="game-feed-panel">
                 <h3>Live Gameplay Feed</h3>
                 <ul id="gameplay-feed-list">
                    <!-- Populated by JS -->
                </ul>
            </div>

            <!-- Top Winners Leaderboard Section -->
            <div class="leaderboard-container">
                <h3>Top Winners</h3>
                 <ul id="top-winners-list">
                    <!-- Populated by JS -->
                </ul>
            </div>
        </div> <!-- End .side-panels-container -->

    </div> <!-- End .main-content-container -->

    <!-- REMOVED: Player Withdrawal Section from this page -->


    <!-- Modal Overlay (Keep) -->
    <div id="modal-overlay" class="hidden">
        <div id="modal-box">
            <h2 id="modal-title">Modal Title</h2>
            <p id="modal-message">This is the modal message.</p>
            <button id="modal-close-btn">Play Again</button>
        </div>
    </div>

    <script src="assets/js/main.js"></script>

</body>
</html>